vm.swappiness=10
vm.vfs_cache_pressure=50
vm.dirty_ratio=15
vm.dirty_background_ratio=5
vm.max_map_count=2147483642
kernel.nmi_watchdog=0
kernel.sched_autogroup_enabled=1
net.ipv4.tcp_congestion_control=bbr
net.core.netdev_max_backlog=5000
