showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
requirements:
    requiredStorage: 20
    requiredRam: 2.0
    internetCheckUrl: http://google.com
    check:
        - storage
        - ram
        - power
        - internet
    required:
        - storage
        - ram
