#!/bin/bash
echo "StrixOS Game Mode Activated!"
for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    echo performance | sudo tee $cpu
done
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
echo "Game Mode Ready!"
